name: Pull Request Merge Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  detectMerge:
    if: github.event.pull_request.merged == true &&  ${{ github.event.pull_request.base.ref == 'main' || github.event.pull_request.head.ref != 'update-cargo-toml' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if pull request was merged
        run: |
          echo "Pull request was merged."
          echo "Source branch: ${{ github.event.pull_request.head.ref }}"
          echo "Target branch: ${{ github.event.pull_request.base.ref }}"
      
        
        
