name: Print Cargo.toml Version

on:
  push:
    branches:
      - main

jobs:
  print_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Cargo.toml Version
        run: |
          cd devprofiler
          cat Cargo.toml | grep -m 1 'version' | awk -F '"' '{print $2}'
