name: Pull Request Checks

on:
  push:
    branches:
      - main

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch remote branches
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git fetch origin ${{ github.event.pull_request.head.ref }}

      - name: Print Old and New Cargo.toml Versions
        id: cargo_version
        run: |
          cd devprofiler
          echo "Old Version:"
          v1=$(git show FETCH_HEAD:./Cargo.toml | grep -m 1 'version' | awk -F '"' '{print $2}')
          echo $v1
          echo "New Version:"      
          v2=$(git log -n 2 --pretty=format:%H | sed -n '2p' | xargs git show:./Cargo.toml | grep -m 1 'version' | awk -F '"' '{print $2}')
          echo $v2

          if [ "$v1" == "$v2" ]; then
            echo "Versions are the same."
          else
            echo "Versions are different."
          fi
