
name: Auto-version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Build Script
        run: |
           git config user.name "VladimirKalita"
           git config user.email "<rishabh21@iitk.ac.in>"
           
      - name: run script
        run: |
           python update.py

      - name: commit updated Cargo.toml
        run: |
           git add devprofiler/Cargo.toml
           git commit -m "Updated code"
           git push origin main

      - name: Build Rust CLI
        run: |
          cd devprofiler
          cargo build --release
          
      - name: Get version from Cargo.toml
        id: get_version
        run: |
          cd devprofiler
          echo "::set-output name=version::$(grep -Po '(?<=version = ")[\d.]+(?=")' Cargo.toml)"
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          
      - name: cargo deb
        run: |
          cargo install  cargo-deb
          
      - name: build binary
        run: |
          cd devprofiler
          cargo deb
          
      - name: Rename Debian Package
        run: mv ./devprofiler/target/debian/*.deb ./devprofiler/target/debian/devprofiler.deb
        
      - name: Upload .deb Package
        id: upload_deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./devprofiler/target/debian/devprofiler.deb
          asset_name: devprofiler.deb
          asset_content_type: application/octet-stream

